export const DARK_COLORS = { bg:'#0d0b1e',bg2:'#1a1535',bg3:'#110e2a',border:'#2a1f4a',text:'#ffffff',textSub:'#e2d9f3',textMuted:'#9575b8',accent:'#fbbf24',primary:'#7c3aed',primary2:'#a855f7',green:'#34d399',red:'#f87171' };
export const LIGHT_COLORS = { bg:'#f8f5ff',bg2:'#ffffff',bg3:'#ede9fe',border:'#ddd6fe',text:'#1e1b4b',textSub:'#312e81',textMuted:'#6d28d9',accent:'#d97706',primary:'#7c3aed',primary2:'#a855f7',green:'#059669',red:'#dc2626' };
export const COLORS = DARK_COLORS;
export const CATEGORIES = ['All','Live TV','Arabic Series','Foreign Series','Arabic Movies','Foreign Movies','Sports','Kids','Religious'];
export const DEMO_USERS = [
  {id:1,name:'Admin',username:'admin',email:'admin@mezstream.com',password:'admin123',wallet:500,avatar:'AD',plan:'premium'},
  {id:2,name:'Test User',username:'user',email:'user@test.com',password:'user123',wallet:0,avatar:'TU',plan:'free'},
];
export const PLANS = [
  {id:'basic',name:{ar:'أساسي',en:'Basic'},price:4.99,period:{ar:'شهرياً',en:'/month'},color:'#6366f1',features:{ar:['قنوات مباشرة','جودة HD','جهاز واحد'],en:['Live Channels','HD','1 Device']}},
  {id:'standard',name:{ar:'قياسي',en:'Standard'},price:9.99,period:{ar:'شهرياً',en:'/month'},color:'#7c3aed',popular:true,features:{ar:['كل القنوات','Full HD','جهازان'],en:['All Channels','Full HD','2 Devices']}},
  {id:'premium',name:{ar:'مميز',en:'Premium'},price:14.99,period:{ar:'شهرياً',en:'/month'},color:'#f59e0b',features:{ar:['كل المحتوى','4K','4 أجهزة'],en:['All Content','4K','4 Devices']}},
];

export const CONTENT = [

  // ══ قنوات مباشرة ══════════════════════════════════════════════════════════
  {id:1,cat:'Live TV',type:'live',name:'Al Jazeera Arabic',nameAr:'الجزيرة العربية',desc:'قناة الجزيرة العربية الإخبارية — أخبار عربية ودولية على مدار الساعة.',image:'https://yt3.googleusercontent.com/oN_i26ADOuQ4PdypHo8yjVXh6QSXZ1kMeYzaRH3hNOlQE1uEUUQ-gkCh0o1rUQ2PM7Qx6QvY2g=s900-c-k-c0x00ffffff-no-rj',colors:['#0a1628','#d4a017'],streamUrl:'https://live-hls-v3-aja.getaj.net/AJA/v3/index.m3u8',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:2,cat:'Live TV',type:'live',name:'Al Jazeera English',nameAr:'الجزيرة الإنجليزية',desc:'Al Jazeera English — Live international news 24/7.',image:'https://pbs.twimg.com/profile_images/2012765494906859520/XkcmI05E.jpg',colors:['#0a1628','#d4a017'],streamUrl:'https://live-hls-web-aje.getaj.net/AJE/index.m3u8',quality:'HD',lang:'en',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:3,cat:'Live TV',type:'live',name:'Al Jazeera Mubasher',nameAr:'الجزيرة مباشر',desc:'قناة الجزيرة مباشر — البث الحي للأحداث والمؤتمرات.',image:'https://www.aljazeera.net/wp-content/uploads/2023/10/%D8%A7%D9%84%D8%A8%D8%AB-%D8%A7%D9%84%D8%AD%D9%8A-1697029464.jpg',colors:['#0a1628','#d4a017'],streamUrl:'https://live-hls-web-ajm.getaj.net/AJM/index.m3u8',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:4,cat:'Live TV',type:'live',name:'RT Arabic',nameAr:'RT عربي',desc:'قناة RT عربي — أخبار من منظور مختلف.',image:'https://www.journalistsupport.net/static/images/dc76031198246fc6e8a7976987e017d0.jpg',colors:['#8b0000','#1a1a1a'],streamUrl:'https://rt-arab.rttv.com/live/rtarab/playlist.m3u8',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:5,cat:'Live TV',type:'live',name:'France 24 Arabic',nameAr:'فرانس 24 عربي',desc:'فرانس 24 بالعربية — أخبار دولية من باريس.',image:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/France_24_logo_%282013%29.svg/250px-France_24_logo_%282013%29.svg.png',colors:['#003087','#e63946'],streamUrl:'https://f24hls-i.akamaihd.net/hls/live/221193/F24_AR_HI/master.m3u8',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:6,cat:'Live TV',type:'live',name:'DW Arabic',nameAr:'DW عربي',desc:'قناة DW بالعربية — أخبار من ألمانيا.',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAGNv7v0Lz1Xs_VASlNEEfx3ynJLpbRFyb5w&s',colors:['#003087','#1a1a1a'],streamUrl:'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8',quality:'HD',lang:'ar',isLive:true},
  {id:7,cat:'Live TV',type:'live',name:'MBC 1',nameAr:'MBC 1',desc:'قناة MBC 1 — أبرز البرامج الترفيهية والمسلسلات العربية.',image:'https://pbs.twimg.com/profile_images/1133033554/mbc-fb_400x400.JPG',colors:['#1a1a2e','#e63946'],streamUrl:'',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:8,cat:'Live TV',type:'live',name:'MBC 2',nameAr:'MBC 2',desc:'قناة MBC 2 — أفلام أجنبية حديثة.',image:'https://aboutmsr.com/wp-content/uploads/2025/07/387-s.webp',colors:['#1a1a2e','#e63946'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:9,cat:'Live TV',type:'live',name:'MBC Drama',nameAr:'MBC دراما',desc:'أفضل المسلسلات العربية والتركية المدبلجة.',image:'https://yt3.googleusercontent.com/K39HHSCPqyqL6Liu05x11jIBFRHKhOeK3RQdcEo_DZyO_OjyUMSTicEoy3hSjGqfO5hs3MkDzXQ=s900-c-k-c0x00ffffff-no-rj',colors:['#1a1a2e','#7c3aed'],streamUrl:'',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:10,cat:'Live TV',type:'live',name:'MBC Action',nameAr:'MBC أكشن',desc:'قناة MBC أكشن — أفلام الحركة.',image:'https://yt3.googleusercontent.com/vlqpeZEEiL70MsCVjCoQreKY4OHXe-rRJkRw8uuXGQYQ5RcgKFCkJEHBKy6_0K-2Yk_Cf7IFNeI=s900-c-k-c0x00ffffff-no-rj',colors:['#1a1a2e','#e63946'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:11,cat:'Live TV',type:'live',name:'MBC 4',nameAr:'MBC 4',desc:'قناة MBC 4 — البرامج الأمريكية.',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNOP-mXEloKBj7Bx9bSR0pZkZx2XaE3LxEaQ&s',colors:['#1a1a2e','#e63946'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:12,cat:'Live TV',type:'live',name:'MBC Bollywood',nameAr:'MBC بوليوود',desc:'أفلام هندية مدبلجة بالعربية.',image:'https://yt3.googleusercontent.com/ytc/AIdro_lr3-zdrrxfLy21Zh4kPN0MwmfuZkmU3imN05ICXZsAnU50=s900-c-k-c0x00ffffff-no-rj',colors:['#ff6b6b','#ffd93d'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:13,cat:'Live TV',type:'live',name:'Rotana Cinema',nameAr:'روتانا سينما',desc:'أحدث الأفلام العربية والأجنبية.',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdmSO-MKFk0c89vzLLbc1ce3xKFXza0ACrIA&s',colors:['#0f0f0f','#d4af37'],streamUrl:'',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:14,cat:'Live TV',type:'live',name:'Rotana Drama',nameAr:'روتانا دراما',desc:'أفضل المسلسلات العربية.',image:'https://yt3.googleusercontent.com/brH-dZa1q6mjEgdqwWwwC8xHde4RTKCMahcg31tF4BrDfsd3GwMU40UpUmlX0RyUt1ayHEIucA=s900-c-k-c0x00ffffff-no-rj',colors:['#0f0f0f','#d4af37'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:15,cat:'Live TV',type:'live',name:'Dubai TV',nameAr:'دبي',desc:'قناة دبي الفضائية.',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4_jcLeRvc8SU5J5MenKFFI0X5bdpvJKSP-w&s',colors:['#1a1a1a','#c9a84c'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:16,cat:'Live TV',type:'live',name:'Abu Dhabi TV',nameAr:'أبوظبي',desc:'قناة أبوظبي — برامج وأخبار من الإمارات.',image:'https://cdn1-m.zahratalkhaleej.ae//wp-content/uploads/2015/03/%D9%82%D9%86%D8%A7%D8%A9-%D8%A3%D8%A8%D9%88%D8%B8%D8%A8%D9%8A.jpg?v=6',colors:['#1a1a1a','#006400'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:17,cat:'Live TV',type:'live',name:'Al Arabiya',nameAr:'العربية',desc:'قناة العربية الإخبارية.',image:'https://static.srpcdigital.com/styles/1037xauto/public/2019/01/01/1546344779846848500.jpg.webp',colors:['#8b0000','#d4af37'],streamUrl:'',quality:'HD',lang:'ar',isLive:true,badge:'أخبار',badgeColor:'#3b82f6'},
  {id:18,cat:'Live TV',type:'live',name:'Sky News Arabia',nameAr:'سكاي نيوز عربية',desc:'أخبار عالمية على مدار الساعة.',image:'https://is1-ssl.mzstatic.com/image/thumb/Purple211/v4/67/a9/17/67a91727-7580-8654-cd66-c8d6cbcaf350/App_Icon-marketing.lsr/1200x630bb.png',colors:['#003087','#e63946'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:19,cat:'Live TV',type:'live',name:'BBC Arabic',nameAr:'BBC عربي',desc:'قناة BBC العربية.',image:'https://ichef.bbci.co.uk/images/ic/1200x675/p07r781v.jpg',colors:['#8b0000','#1a1a1a'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:20,cat:'Live TV',type:'live',name:'Al Nahar',nameAr:'النهار',desc:'قناة النهار المصرية.',image:'https://pbs.twimg.com/profile_images/1449381585798402050/nF2OkOe2_400x400.jpg',colors:['#ff6600','#1a1a1a'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:21,cat:'Live TV',type:'live',name:'Nile TV',nameAr:'النيل',desc:'قناة النيل الدولية من مصر.',image:'https://pbs.twimg.com/profile_images/1392479899090251786/XvEd1Bhf_400x400.jpg',colors:['#0a5c36','#d4af37'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:22,cat:'Live TV',type:'live',name:'Kuwait TV',nameAr:'الكويت',desc:'قناة الكويت الرسمية.',image:'https://pbs.twimg.com/profile_images/1244924833783689216/Nf3XHHBH_400x400.jpg',colors:['#007a3d','#ce1126'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:23,cat:'Live TV',type:'live',name:'Shahid Live',nameAr:'شاهد مباشر',desc:'البث المباشر من منصة شاهد.',image:'https://play-lh.googleusercontent.com/3opVGBh3cDm6aMgFgJNOXLBmQIRE5UbvBE4WLSB5NVFRk9nRp2UHB4Td8h6T3L8Gg',colors:['#1a0a3b','#7b2d8b'],streamUrl:'',quality:'4K',lang:'ar',isLive:true,badge:'4K',badgeColor:'#7c3aed'},

  // ══ رياضة ══════════════════════════════════════════════════════════════════
  {id:101,cat:'Sports',type:'live',name:'beIN Sports 1',nameAr:'بي إن سبورتس 1',desc:'دوري أبطال أوروبا والدوريات الكبرى.',image:'https://pbs.twimg.com/profile_images/1488149649625423875/9JRJXYjy_400x400.jpg',colors:['#0d1b2a','#e63946'],streamUrl:'',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:102,cat:'Sports',type:'live',name:'beIN Sports 2',nameAr:'بي إن سبورتس 2',desc:'الدوريات الأوروبية الكبرى.',image:'https://pbs.twimg.com/profile_images/1488149649625423875/9JRJXYjy_400x400.jpg',colors:['#0d1b2a','#e63946'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:103,cat:'Sports',type:'live',name:'beIN Sports 3',nameAr:'بي إن سبورتس 3',desc:'البطولات الآسيوية والأفريقية.',image:'https://pbs.twimg.com/profile_images/1488149649625423875/9JRJXYjy_400x400.jpg',colors:['#0d1b2a','#e63946'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:104,cat:'Sports',type:'live',name:'SSC Sport 1',nameAr:'SSC رياضة 1',desc:'الدوري السعودي للمحترفين.',image:'https://pbs.twimg.com/profile_images/1466408538516934659/QYLhsNLZ_400x400.jpg',colors:['#0d1b2a','#1565c0'],streamUrl:'',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#ef4444'},
  {id:105,cat:'Sports',type:'live',name:'SSC Sport 2',nameAr:'SSC رياضة 2',desc:'مباريات الدوري السعودي.',image:'https://pbs.twimg.com/profile_images/1466408538516934659/QYLhsNLZ_400x400.jpg',colors:['#0d1b2a','#1565c0'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:106,cat:'Sports',type:'live',name:'Abu Dhabi Sports',nameAr:'أبوظبي الرياضية',desc:'البطولات المحلية والدولية.',image:'https://pbs.twimg.com/profile_images/1671481722827763712/nHFQS23Q_400x400.jpg',colors:['#006400','#d4af37'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:107,cat:'Sports',type:'live',name:'Dubai Sports',nameAr:'دبي الرياضية',desc:'كرة القدم والرياضات المختلفة.',image:'https://pbs.twimg.com/profile_images/1408403907398610948/o-aQIbFB_400x400.jpg',colors:['#1a1a1a','#c9a84c'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},

  // ══ دينية ══════════════════════════════════════════════════════════════════
  {id:150,cat:'Religious',type:'live',name:'Makkah TV',nameAr:'قناة مكة المكرمة',desc:'البث المباشر من المسجد الحرام.',image:'https://i.ytimg.com/vi/4Dp3GxZjfnY/maxresdefault.jpg',colors:['#006400','#d4af37'],streamUrl:'https://bin79.ott.cdn.net.sa:443/live/4000026/index.m3u8',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#10b981'},
  {id:151,cat:'Religious',type:'live',name:'Madinah TV',nameAr:'قناة المدينة المنورة',desc:'البث المباشر من المسجد النبوي الشريف.',image:'https://i.ytimg.com/vi/h1Lr7R7xAH0/maxresdefault.jpg',colors:['#006400','#d4af37'],streamUrl:'https://bin79.ott.cdn.net.sa:443/live/4000027/index.m3u8',quality:'HD',lang:'ar',isLive:true,badge:'مباشر',badgeColor:'#10b981'},
  {id:152,cat:'Religious',type:'live',name:'Iqraa TV',nameAr:'اقرأ',desc:'المحتوى الإسلامي التعليمي.',image:'https://pbs.twimg.com/profile_images/1256581547773693952/O9Gp9NpL_400x400.jpg',colors:['#006400','#d4af37'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:153,cat:'Religious',type:'live',name:'Al Resala TV',nameAr:'الرسالة',desc:'قناة الرسالة الإسلامية.',image:'https://pbs.twimg.com/profile_images/1631270866278707202/YCPp4pNg_400x400.jpg',colors:['#006400','#d4af37'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},

  // ══ أطفال ══════════════════════════════════════════════════════════════════
  {id:200,cat:'Kids',type:'live',name:'Baraem',nameAr:'براعم',desc:'محتوى تعليمي آمن للأطفال.',image:'https://pbs.twimg.com/profile_images/1117378876245159937/KT5Da5PG_400x400.png',colors:['#ff6b6b','#ffd93d'],streamUrl:'',quality:'HD',lang:'ar',isLive:true,badge:'أطفال',badgeColor:'#10b981'},
  {id:201,cat:'Kids',type:'live',name:'MBC 3',nameAr:'MBC 3',desc:'قناة MBC 3 للأطفال.',image:'https://www.mbc.net/content/dam/mbc/logo/MBC3-Logo.png',colors:['#ff6b6b','#1565c0'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:202,cat:'Kids',type:'live',name:'Spacetoon',nameAr:'سبيستون',desc:'رسوم متحركة للأطفال.',image:'https://play-lh.googleusercontent.com/0L3T7BXLB_W_SIr0VpUvjPbFPqxpxRJMxdZCTGHcgUJNq-EpqXBHqnuTtMQhd-wIA',colors:['#ff6b6b','#ffd93d'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},
  {id:203,cat:'Kids',type:'live',name:'Jeem TV',nameAr:'جيم',desc:'محتوى تفاعلي للأطفال.',image:'https://play-lh.googleusercontent.com/dj3vNH6RLnpkKH7RW6zNaUAaYy_Gx3RA_eHaU4SsBSe0DdSRnkVbGRh0mDpCqmJJx0',colors:['#ff6b6b','#ffd93d'],streamUrl:'',quality:'HD',lang:'ar',isLive:true},

  // ══ مسلسلات عربية ══════════════════════════════════════════════════════════
  {id:300,cat:'Arabic Series',type:'series',name:'باب الحارة',nameAr:'باب الحارة',desc:'المسلسل الاجتماعي الشهير في حارة شامية أيام الاحتلال الفرنسي.',image:'https://shahid.mbc.net/mediaObject/2024/Hanin/Aug/Poster_bab_alhara/original/Poster_bab_alhara.jpg',colors:['#3b1f08','#c8a84b'],streamUrl:'',quality:'HD',lang:'ar',year:2006,episodes:50,rating:8.5,genre:{ar:'اجتماعي',en:'Social'}},
  {id:301,cat:'Arabic Series',type:'series',name:'الهيبة',nameAr:'الهيبة',desc:'مسلسل لبناني أكشن عن زعيم قبيلة على الحدود.',image:'https://almashhadalaraby.com/photos/61585b4d8d680.jpeg',colors:['#1a1a2e','#e63946'],streamUrl:'',quality:'Full HD',lang:'ar',year:2017,episodes:30,rating:8.7,genre:{ar:'أكشن',en:'Action'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:302,cat:'Arabic Series',type:'series',name:'قيامة أرطغرل',nameAr:'قيامة أرطغرل',desc:'ملحمة تاريخية تركية مدبلجة عن مؤسس الدولة العثمانية.',image:'https://upload.wikimedia.org/wikipedia/ar/f/fe/Dirili%C5%9F-_Ertu%C4%9Frul_S1.jpg',colors:['#2c1810','#8b4513'],streamUrl:'',quality:'HD',lang:'ar',year:2014,episodes:150,rating:9.1,genre:{ar:'تاريخي',en:'Historical'},badge:'الأعلى',badgeColor:'#f59e0b'},
  {id:303,cat:'Arabic Series',type:'series',name:'المؤسس عثمان',nameAr:'قيامة عثمان',desc:'قصة عثمان بن أرطغرل مؤسس الدولة العثمانية.',image:'https://image.tmdb.org/t/p/original/oW4Lt0J4cJrRrk66q9bkPNQTuwp.jpg',colors:['#2c1810','#8b4513'],streamUrl:'',quality:'HD',lang:'ar',year:2019,episodes:100,rating:8.9,genre:{ar:'تاريخي',en:'Historical'}},
  {id:304,cat:'Arabic Series',type:'series',name:'حريم السلطان',nameAr:'حريم السلطان',desc:'قصة السلطان سليمان القانوني وحريمه.',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8_8-JWO_hKDkJcTZ4zPNdblH-eo1BqA0X3g&s',colors:['#8b0000','#d4af37'],streamUrl:'',quality:'HD',lang:'ar',year:2011,episodes:139,rating:7.9,genre:{ar:'تاريخي',en:'Historical'},badge:'كلاسيك',badgeColor:'#f59e0b'},
  {id:305,cat:'Arabic Series',type:'series',name:'وضع أمني',nameAr:'وضع أمني',desc:'مسلسل أكشن سعودي عن مكافحة الإرهاب.',image:'https://i.ytimg.com/vi/7JqKxE0MfMM/maxresdefault.jpg',colors:['#0d1b2a','#1565c0'],streamUrl:'',quality:'4K',lang:'ar',year:2022,episodes:20,rating:8.3,genre:{ar:'إثارة',en:'Thriller'},badge:'4K',badgeColor:'#7c3aed'},
  {id:306,cat:'Arabic Series',type:'series',name:'عروس بيروت',nameAr:'عروس بيروت',desc:'صراع الطبقات في بيروت.',image:'https://i.ytimg.com/vi/U6RFKL5tpJ0/maxresdefault.jpg',colors:['#0a1628','#c0392b'],streamUrl:'',quality:'Full HD',lang:'ar',year:2019,episodes:40,rating:7.8,genre:{ar:'رومانسي',en:'Romance'}},
  {id:307,cat:'Arabic Series',type:'series',name:'الاختيار',nameAr:'الاختيار',desc:'يوثق بطولات الجيش والشرطة المصرية.',image:'https://upload.wikimedia.org/wikipedia/ar/c/c1/%D9%85%D9%84%D8%B5%D9%82_%D9%85%D8%B3%D9%84%D8%B3%D9%84_%D8%A7%D9%84%D8%A7%D8%AE%D8%AA%D9%8A%D8%A7%D8%B1.jpg',colors:['#0d1b2a','#c8a84b'],streamUrl:'',quality:'Full HD',lang:'ar',year:2020,episodes:30,rating:8.5,genre:{ar:'حربي',en:'War'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:308,cat:'Arabic Series',type:'series',name:'كلبش',nameAr:'كلبش',desc:'ضابط شرطة في مواجهة عالم الجريمة.',image:'https://i.ytimg.com/vi/m0b4xKGEGVY/maxresdefault.jpg',colors:['#1a1a2e','#e63946'],streamUrl:'',quality:'HD',lang:'ar',year:2017,episodes:30,rating:8.3,genre:{ar:'جريمة',en:'Crime'}},
  {id:309,cat:'Arabic Series',type:'series',name:'العاصوف',nameAr:'العاصوف',desc:'مسلسل سعودي تاريخي عن السبعينيات.',image:'https://i.ytimg.com/vi/C_e1R5m3Dmk/maxresdefault.jpg',colors:['#3b1f08','#c8a84b'],streamUrl:'',quality:'Full HD',lang:'ar',year:2017,episodes:30,rating:8.4,genre:{ar:'تاريخي',en:'Historical'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:310,cat:'Arabic Series',type:'series',name:'طاش ما طاش',nameAr:'طاش ما طاش',desc:'المسلسل الكوميدي السعودي الأشهر.',image:'https://elalem.info/IMG/logo/1-945.jpg?1668796266',colors:['#ff6600','#1a1a1a'],streamUrl:'',quality:'HD',lang:'ar',year:1993,episodes:300,rating:8.6,genre:{ar:'كوميدي',en:'Comedy'},badge:'كلاسيك',badgeColor:'#f59e0b'},
  {id:311,cat:'Arabic Series',type:'series',name:'مرايا',nameAr:'مرايا',desc:'المسلسل الكوميدي السوري الأشهر.',image:'https://i.ytimg.com/vi/NRBjuOiFBmc/maxresdefault.jpg',colors:['#1a1a2e','#c8a84b'],streamUrl:'',quality:'HD',lang:'ar',year:1997,episodes:200,rating:8.3,genre:{ar:'كوميدي',en:'Comedy'},badge:'كلاسيك',badgeColor:'#f59e0b'},
  {id:312,cat:'Arabic Series',type:'series',name:'سلسال الدم',nameAr:'سلسال الدم',desc:'قصة ثأر وانتقام بين عائلتين.',image:'https://i.ytimg.com/vi/6YF8I5A0ZMQ/maxresdefault.jpg',colors:['#8b0000','#1a1a1a'],streamUrl:'',quality:'HD',lang:'ar',year:2012,episodes:90,rating:7.6,genre:{ar:'درامي',en:'Drama'}},
  {id:313,cat:'Arabic Series',type:'series',name:'نور',nameAr:'نور',desc:'مسلسل تركي مدبلج — قصة حب بين شخصيتين.',image:'https://i.ytimg.com/vi/L56sJyFYL4U/maxresdefault.jpg',colors:['#1a0a3b','#9b59b6'],streamUrl:'',quality:'HD',lang:'ar',year:2008,episodes:80,rating:8.2,genre:{ar:'رومانسي',en:'Romance'}},
  {id:314,cat:'Arabic Series',type:'series',name:'هجمة مرتدة',nameAr:'هجمة مرتدة',desc:'فريق خاص لمكافحة الجريمة المنظمة.',image:'https://i.ytimg.com/vi/ZoxJjBF3b_k/maxresdefault.jpg',colors:['#0d1b2a','#e63946'],streamUrl:'',quality:'HD',lang:'ar',year:2019,episodes:30,rating:7.9,genre:{ar:'أكشن',en:'Action'}},

  // ══ مسلسلات أجنبية ═════════════════════════════════════════════════════════
  {id:400,cat:'Foreign Series',type:'series',name:'Breaking Bad',nameAr:'بريكينج باد',desc:'مدرس كيمياء يتحول إلى صانع مخدرات.',image:'https://cdn.salla.sa/wQwYX/LXyizk4gbYDGBvilO93kglucDyH7vm7dQWHCI7IF.png',colors:['#1a1a1a','#2ecc71'],streamUrl:'',quality:'Full HD',lang:'en',year:2008,episodes:62,rating:9.5,genre:{ar:'جريمة',en:'Crime'},badge:'الأفضل',badgeColor:'#f59e0b'},
  {id:401,cat:'Foreign Series',type:'series',name:'Game of Thrones',nameAr:'صراع العروش',desc:'ملحمة فانتازيا عن عائلات تتنافس على العرش.',image:'https://m.media-amazon.com/images/M/MV5BN2IzYzBiOTQtNGZmMi00NDI5LTgxMzMtN2EzZjA1NjhlOGMxXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg',colors:['#1a1a2e','#d4af37'],streamUrl:'',quality:'4K',lang:'en',year:2011,episodes:73,rating:9.2,genre:{ar:'فانتازيا',en:'Fantasy'},badge:'4K',badgeColor:'#7c3aed'},
  {id:402,cat:'Foreign Series',type:'series',name:'Money Heist',nameAr:'لا كاسا دي بابيل',desc:'سطو على دار سك العملة الإسبانية.',image:'https://m.media-amazon.com/images/M/MV5BZDg5MTM0ODItNWFlZi00NjVlLTk2YzktMDc5MWUwMGI2NTEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',colors:['#8b0000','#1a1a1a'],streamUrl:'',quality:'Full HD',lang:'es',year:2017,episodes:48,rating:8.3,genre:{ar:'جريمة',en:'Crime'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:403,cat:'Foreign Series',type:'series',name:'Stranger Things',nameAr:'أشياء غريبة',desc:'أطفال يكتشفون عالماً خفياً مرعباً.',image:'https://m.media-amazon.com/images/M/MV5BMDZkYmVhNjMtNWU4MC00MDQxLWE3MjYtZGMzZWI1ZjhlOWJmXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',colors:['#0d0d0d','#e63946'],streamUrl:'',quality:'Full HD',lang:'en',year:2016,episodes:34,rating:8.7,genre:{ar:'رعب',en:'Horror'}},
  {id:404,cat:'Foreign Series',type:'series',name:'Squid Game',nameAr:'لعبة الحبار',desc:'ألعاب طفولية بحياة أشخاص مدينين.',image:'https://m.media-amazon.com/images/M/MV5BYWE3MDVkN2EtNjQ5MS00ZDQ4LTliNzYtMjc2YWMzMDEwMTA3XkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_FMjpg_UX1000_.jpg',colors:['#0d4f3c','#e63946'],streamUrl:'',quality:'4K',lang:'ko',year:2021,episodes:9,rating:8.0,genre:{ar:'إثارة',en:'Thriller'},badge:'4K',badgeColor:'#7c3aed'},
  {id:405,cat:'Foreign Series',type:'series',name:'The Crown',nameAr:'التاج',desc:'تاريخ الأسرة المالكة البريطانية.',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWJptZtThkq33e7oTzWZELYV5FHAbymASwFg&s',colors:['#1a1a2e','#d4af37'],streamUrl:'',quality:'Full HD',lang:'en',year:2016,episodes:60,rating:8.6,genre:{ar:'تاريخي',en:'Historical'}},
  {id:406,cat:'Foreign Series',type:'series',name:'Dark',nameAr:'دارك',desc:'مسلسل ألماني عن السفر عبر الزمن.',image:'https://m.media-amazon.com/images/M/MV5BOWJjMGViY2UtNTAzNS00ZGFjLWFkNTMtMDBiMDMyZTM1NTY3XkEyXkFqcGc@._V1_.jpg',colors:['#0d0d0d','#1565c0'],streamUrl:'',quality:'Full HD',lang:'de',year:2017,episodes:26,rating:8.8,genre:{ar:'خيال علمي',en:'Sci-Fi'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:407,cat:'Foreign Series',type:'series',name:'Narcos',nameAr:'ناركوس',desc:'قصة بابلو إسكوبار وإمبراطورية المخدرات.',image:'https://www.shorouknews.com/uploadedimages/Other/original/sdfdsdsds.jpg',colors:['#1a1a1a','#d4af37'],streamUrl:'',quality:'Full HD',lang:'en',year:2015,episodes:30,rating:8.8,genre:{ar:'جريمة',en:'Crime'}},
  {id:408,cat:'Foreign Series',type:'series',name:'The Boys',nameAr:'ذا بويز',desc:'مقاتلون يواجهون أبطالاً خارقين فاسدين.',image:'https://m.media-amazon.com/images/I/71mdM0xPT+L._AC_UF1000,1000_QL80_.jpg',colors:['#0d1b2a','#e63946'],streamUrl:'',quality:'4K',lang:'en',year:2019,episodes:32,rating:8.7,genre:{ar:'أكشن',en:'Action'},badge:'4K',badgeColor:'#7c3aed'},
  {id:409,cat:'Foreign Series',type:'series',name:'Peaky Blinders',nameAr:'بيكي بلايندرز',desc:'عائلة إجرامية في برمنغهام.',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvoOB4uepATFbUbD90pj0sqEkaTeyKKe7efw&s',colors:['#1a1a1a','#8b0000'],streamUrl:'',quality:'Full HD',lang:'en',year:2013,episodes:36,rating:8.8,genre:{ar:'جريمة',en:'Crime'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:410,cat:'Foreign Series',type:'series',name:'House of the Dragon',nameAr:'بيت التنين',desc:'قصة سقوط بيت تارغاريان.',image:'https://osn-artwork.anghcdn.co/portrait_tt_SN19958/19958-2_PTT.jpg',colors:['#1a1a2e','#c8a84b'],streamUrl:'',quality:'4K',lang:'en',year:2022,episodes:20,rating:8.5,genre:{ar:'فانتازيا',en:'Fantasy'},badge:'4K',badgeColor:'#7c3aed'},
  {id:411,cat:'Foreign Series',type:'series',name:'The Last of Us',nameAr:'ذا لاست أوف أس',desc:'رحلة عبر عالم ما بعد الوباء.',image:'https://m.media-amazon.com/images/M/MV5BZGUzYTI3M2EtZmM0Yy00NGUyLWI4ODEtN2Q3ZGJlYzhhZjU3XkEyXkFqcGdeQXVyNTM0OTY1OQ@@._V1_FMjpg_UX1000_.jpg',colors:['#2c4a1a','#8b4513'],streamUrl:'',quality:'4K',lang:'en',year:2023,episodes:9,rating:8.8,genre:{ar:'رعب',en:'Horror'},badge:'جديد',badgeColor:'#10b981'},
  {id:412,cat:'Foreign Series',type:'series',name:'Wednesday',nameAr:'ويدنسداي',desc:'ويدنسداي في مدرسة مليئة بالأسرار.',image:'https://m.media-amazon.com/images/M/MV5BNzg0MjcxNjYtZGY4NS00YzE4LWI3OGYtMmZlZGNmMzM5ZjU3XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',colors:['#0d0d0d','#8b0000'],streamUrl:'',quality:'Full HD',lang:'en',year:2022,episodes:8,rating:8.1,genre:{ar:'غموض',en:'Mystery'}},
  {id:413,cat:'Foreign Series',type:'series',name:'Better Call Saul',nameAr:'بيتر كول سول',desc:'قصة المحامي سول قبل أحداث Breaking Bad.',image:'https://upload.wikimedia.org/wikipedia/ar/e/e7/%D9%85%D9%84%D8%B5%D9%82_%D9%85%D8%B3%D9%84%D8%B3%D9%84_%D9%85%D9%86_%D8%A7%D9%84%D8%A3%D9%81%D8%B6%D9%84_%D8%A7%D9%84%D8%A7%D8%AA%D8%B5%D8%A7%D9%84_%D8%A8%D8%B3%D9%88%D9%84.jpeg',colors:['#1a1a1a','#d4af37'],streamUrl:'',quality:'Full HD',lang:'en',year:2015,episodes:63,rating:9.0,genre:{ar:'جريمة',en:'Crime'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:414,cat:'Foreign Series',type:'series',name:'Severance',nameAr:'سيفيرانس',desc:'فصل ذاكرة العمل عن الحياة الشخصية.',image:'https://images.justwatch.com/poster/264516782/s332/season-1.jpg',colors:['#1a1a2e','#1565c0'],streamUrl:'',quality:'4K',lang:'en',year:2022,episodes:9,rating:8.7,genre:{ar:'إثارة',en:'Thriller'},badge:'جديد',badgeColor:'#10b981'},
  {id:415,cat:'Foreign Series',type:'series',name:'Chernobyl',nameAr:'تشيرنوبيل',desc:'الكارثة النووية الأسوأ في التاريخ.',image:'https://upload.wikimedia.org/wikipedia/ar/a/a7/Chernobyl_2019_Miniseries.jpg',colors:['#2c4a1a','#8b8b00'],streamUrl:'',quality:'Full HD',lang:'en',year:2019,episodes:5,rating:9.4,genre:{ar:'تاريخي',en:'Historical'},badge:'الأفضل',badgeColor:'#f59e0b'},
  {id:416,cat:'Foreign Series',type:'series',name:'Black Mirror',nameAr:'المرآة السوداء',desc:'مخاطر التكنولوجيا والمستقبل.',image:'https://m.media-amazon.com/images/M/MV5BYTM3YWVhMGMtNmY5My00ZDNkLTgxOGYtYTFmNjQ5ZGNmNTJiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',colors:['#0d0d0d','#1565c0'],streamUrl:'',quality:'Full HD',lang:'en',year:2011,episodes:22,rating:8.8,genre:{ar:'خيال علمي',en:'Sci-Fi'},badge:'مميز',badgeColor:'#f59e0b'},

  // ══ أفلام عربية ════════════════════════════════════════════════════════════
  {id:500,cat:'Arabic Movies',type:'movie',name:'الفيل الأزرق',nameAr:'الفيل الأزرق',desc:'طبيب نفسي يواجه صديق طفولته في مستشفى المجانين.',image:'https://i.ytimg.com/vi/fRXtxSCxpmg/maxresdefault.jpg',colors:['#0a1628','#1565c0'],streamUrl:'',quality:'Full HD',lang:'ar',year:2014,duration:137,rating:8.1,genre:{ar:'رعب',en:'Horror'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:501,cat:'Arabic Movies',type:'movie',name:'الفيل الأزرق 2',nameAr:'الفيل الأزرق 2',desc:'الجزء الثاني من الفيلم المرعب.',image:'https://i.ytimg.com/vi/8S1b0MqVMq8/maxresdefault.jpg',colors:['#0a1628','#1565c0'],streamUrl:'',quality:'Full HD',lang:'ar',year:2019,duration:130,rating:7.8,genre:{ar:'رعب',en:'Horror'}},
  {id:502,cat:'Arabic Movies',type:'movie',name:'ولاد رزق',nameAr:'ولاد رزق',desc:'ثلاثة أشقاء في عالم الجريمة.',image:'https://i.ytimg.com/vi/zWEBkp37hKs/maxresdefault.jpg',colors:['#0d1b2a','#e63946'],streamUrl:'',quality:'Full HD',lang:'ar',year:2015,duration:120,rating:7.9,genre:{ar:'أكشن',en:'Action'}},
  {id:503,cat:'Arabic Movies',type:'movie',name:'ولاد رزق 2',nameAr:'ولاد رزق 2',desc:'الجزء الثاني — مزيد من الأكشن.',image:'https://i.ytimg.com/vi/TKJjYi4ISME/maxresdefault.jpg',colors:['#0d1b2a','#e63946'],streamUrl:'',quality:'Full HD',lang:'ar',year:2018,duration:125,rating:8.0,genre:{ar:'أكشن',en:'Action'}},
  {id:504,cat:'Arabic Movies',type:'movie',name:'كيرة والجن',nameAr:'كيرة والجن',desc:'فيلم تاريخي مصري في عهد الاحتلال البريطاني.',image:'https://i.ytimg.com/vi/vS5KiX2hMSI/maxresdefault.jpg',colors:['#3b1f08','#c8a84b'],streamUrl:'',quality:'Full HD',lang:'ar',year:2022,duration:145,rating:8.2,genre:{ar:'تاريخي',en:'Historical'},badge:'جديد',badgeColor:'#10b981'},
  {id:505,cat:'Arabic Movies',type:'movie',name:'تراب الماس',nameAr:'تراب الماس',desc:'عالم المافيا والتهريب في مصر.',image:'https://i.ytimg.com/vi/MuXt3yAOFYs/maxresdefault.jpg',colors:['#1a1a1a','#d4af37'],streamUrl:'',quality:'Full HD',lang:'ar',year:2018,duration:120,rating:7.6,genre:{ar:'جريمة',en:'Crime'}},
  {id:506,cat:'Arabic Movies',type:'movie',name:'الكنز',nameAr:'الكنز',desc:'مغامرة تاريخية عن البحث عن كنز فرعوني.',image:'https://i.ytimg.com/vi/Tg5jH-KJCe4/maxresdefault.jpg',colors:['#c8a84b','#3b1f08'],streamUrl:'',quality:'Full HD',lang:'ar',year:2017,duration:140,rating:7.8,genre:{ar:'مغامرة',en:'Adventure'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:507,cat:'Arabic Movies',type:'movie',name:'يوم 13',nameAr:'يوم 13',desc:'فيلم رعب مصري مرعب.',image:'https://i.ytimg.com/vi/NaobW-CXPBI/maxresdefault.jpg',colors:['#0d0d0d','#8b0000'],streamUrl:'',quality:'Full HD',lang:'ar',year:2022,duration:120,rating:7.9,genre:{ar:'رعب',en:'Horror'}},
  {id:508,cat:'Arabic Movies',type:'movie',name:'ريش',nameAr:'ريش',desc:'فيلم مصري حاز على جوائز دولية.',image:'https://i.ytimg.com/vi/l6t3A_byJsY/maxresdefault.jpg',colors:['#1a1a1a','#c8a84b'],streamUrl:'',quality:'Full HD',lang:'ar',year:2021,duration:115,rating:7.7,genre:{ar:'درامي',en:'Drama'},badge:'جوائز',badgeColor:'#f59e0b'},
  {id:509,cat:'Arabic Movies',type:'movie',name:'أهواك',nameAr:'أهواك',desc:'فيلم رومانسي مصري في عصر الرقمنة.',image:'https://i.ytimg.com/vi/aBdBUKYOoio/maxresdefault.jpg',colors:['#9b59b6','#1a1a1a'],streamUrl:'',quality:'HD',lang:'ar',year:2021,duration:115,rating:7.4,genre:{ar:'رومانسي',en:'Romance'}},

  // ══ أفلام أجنبية ═══════════════════════════════════════════════════════════
  {id:600,cat:'Foreign Movies',type:'movie',name:'Inception',nameAr:'إنسبشن',desc:'لص يسرق الأسرار من عقول الناس أثناء نومهم.',image:'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg',colors:['#0d1b2a','#1565c0'],streamUrl:'',quality:'4K',lang:'en',year:2010,duration:148,rating:8.8,genre:{ar:'خيال علمي',en:'Sci-Fi'},badge:'كلاسيك',badgeColor:'#f59e0b'},
  {id:601,cat:'Foreign Movies',type:'movie',name:'The Dark Knight',nameAr:'فارس الظلام',desc:'باتمان يواجه الجوكر لإنقاذ غوثام.',image:'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_FMjpg_UX1000_.jpg',colors:['#0d0d0d','#1565c0'],streamUrl:'',quality:'4K',lang:'en',year:2008,duration:152,rating:9.0,genre:{ar:'أكشن',en:'Action'},badge:'الأفضل',badgeColor:'#f59e0b'},
  {id:602,cat:'Foreign Movies',type:'movie',name:'Avengers: Endgame',nameAr:'المنتقمون: نهاية اللعبة',desc:'معركة الحسم النهائية ضد ثانوس.',image:'https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_FMjpg_UX1000_.jpg',colors:['#1a1a2e','#e63946'],streamUrl:'',quality:'4K',lang:'en',year:2019,duration:181,rating:8.4,genre:{ar:'أكشن',en:'Action'},badge:'4K',badgeColor:'#7c3aed'},
  {id:603,cat:'Foreign Movies',type:'movie',name:'Interstellar',nameAr:'إنترستيلار',desc:'رحلة عبر ثقب دودي بحثاً عن كوكب جديد.',image:'https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg',colors:['#0d1b2a','#0a4f6f'],streamUrl:'',quality:'4K',lang:'en',year:2014,duration:169,rating:8.6,genre:{ar:'خيال علمي',en:'Sci-Fi'},badge:'4K',badgeColor:'#7c3aed'},
  {id:604,cat:'Foreign Movies',type:'movie',name:'The Godfather',nameAr:'العراب',desc:'زعيم المافيا وصراع السيطرة على إمبراطوريته.',image:'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_FMjpg_UX1000_.jpg',colors:['#1a1a1a','#d4af37'],streamUrl:'',quality:'Full HD',lang:'en',year:1972,duration:175,rating:9.2,genre:{ar:'جريمة',en:'Crime'},badge:'كلاسيك',badgeColor:'#f59e0b'},
  {id:605,cat:'Foreign Movies',type:'movie',name:'Parasite',nameAr:'طفيلي',desc:'عائلة فقيرة تتسلل إلى حياة عائلة ثرية.',image:'https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_FMjpg_UX1000_.jpg',colors:['#1a1a1a','#2ecc71'],streamUrl:'',quality:'Full HD',lang:'ko',year:2019,duration:132,rating:8.5,genre:{ar:'إثارة',en:'Thriller'},badge:'أوسكار',badgeColor:'#f59e0b'},
  {id:606,cat:'Foreign Movies',type:'movie',name:'Oppenheimer',nameAr:'أوبنهايمر',desc:'مخترع القنبلة الذرية وصراعه الداخلي.',image:'https://m.media-amazon.com/images/M/MV5BMDBmYTZjNjUtN2M1MS00MTQ2LTk2ODgtNzc2M2QyZGE5NTVjXkEyXkFqcGdeQXVyNzAwMjU2MTY@._V1_FMjpg_UX1000_.jpg',colors:['#0d1b2a','#c8a84b'],streamUrl:'',quality:'4K',lang:'en',year:2023,duration:180,rating:8.6,genre:{ar:'تاريخي',en:'Historical'},badge:'جديد',badgeColor:'#10b981'},
  {id:607,cat:'Foreign Movies',type:'movie',name:'Top Gun: Maverick',nameAr:'توب غان: مافيريك',desc:'مافيريك يدرب الجيل الجديد من الطيارين.',image:'https://m.media-amazon.com/images/M/MV5BZWYzOGEwNUgtNjU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_FMjpg_UX1000_.jpg',colors:['#0d1b2a','#c8a84b'],streamUrl:'',quality:'4K',lang:'en',year:2022,duration:131,rating:8.3,genre:{ar:'أكشن',en:'Action'},badge:'4K',badgeColor:'#7c3aed'},
  {id:608,cat:'Foreign Movies',type:'movie',name:'The Shawshank Redemption',nameAr:'خلاص من شاوشانك',desc:'رجل بريء يجد الأمل داخل سجن قاسٍ.',image:'https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NiYyLTg3MzMtYjIyNzIxMjZkMDFmXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_FMjpg_UX1000_.jpg',colors:['#1a1a1a','#d4af37'],streamUrl:'',quality:'Full HD',lang:'en',year:1994,duration:142,rating:9.3,genre:{ar:'درامي',en:'Drama'},badge:'كلاسيك',badgeColor:'#f59e0b'},
  {id:609,cat:'Foreign Movies',type:'movie',name:'Joker',nameAr:'جوكر',desc:'كيف تحول أرثر فليك إلى الجوكر.',image:'https://m.media-amazon.com/images/M/MV5BNGVjNWI4ZGUtNzE0MS00YTJmLWE0ZDctN2ZiYTk2YmI3NTYyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_FMjpg_UX1000_.jpg',colors:['#8b0000','#d4af37'],streamUrl:'',quality:'4K',lang:'en',year:2019,duration:122,rating:8.4,genre:{ar:'درامي',en:'Drama'},badge:'مميز',badgeColor:'#f59e0b'},
  {id:610,cat:'Foreign Movies',type:'movie',name:'Avatar: The Way of Water',nameAr:'أفاتار 2',desc:'سكوللي وعائلته يواجهون تهديداً جديداً.',image:'https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_FMjpg_UX1000_.jpg',colors:['#0a4f6f','#1565c0'],streamUrl:'',quality:'4K',lang:'en',year:2022,duration:192,rating:7.6,genre:{ar:'خيال علمي',en:'Sci-Fi'},badge:'4K',badgeColor:'#7c3aed'},
  {id:611,cat:'Foreign Movies',type:'movie',name:'Spider-Man: No Way Home',nameAr:'سبايدر مان',desc:'بيتر باركر يفتح بوابات متعددة الأكوان.',image:'https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_FMjpg_UX1000_.jpg',colors:['#8b0000','#003087'],streamUrl:'',quality:'Full HD',lang:'en',year:2021,duration:148,rating:8.2,genre:{ar:'أكشن',en:'Action'}},
  {id:612,cat:'Foreign Movies',type:'movie',name:'Forrest Gump',nameAr:'فورست غامب',desc:'رجل بسيط يعيش حياة استثنائية.',image:'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yjk1LTgxZWEtYWMxZWFiZGNiZTIxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_FMjpg_UX1000_.jpg',colors:['#3b1f08','#c8a84b'],streamUrl:'',quality:'Full HD',lang:'en',year:1994,duration:142,rating:8.8,genre:{ar:'درامي',en:'Drama'},badge:'كلاسيك',badgeColor:'#f59e0b'},
  {id:613,cat:'Foreign Movies',type:'movie',name:'Dune: Part Two',nameAr:'ديون: الجزء الثاني',desc:'بول أتريدس يقود الثورة على أراكيس.',image:'https://m.media-amazon.com/images/M/MV5BN2QyZGU4ZDctOWMzMy00NTc5LThlOGQtODhmNDBiNTI3ZWIyXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_FMjpg_UX1000_.jpg',colors:['#c8a84b','#3b1f08'],streamUrl:'',quality:'4K',lang:'en',year:2024,duration:166,rating:8.5,genre:{ar:'خيال علمي',en:'Sci-Fi'},badge:'جديد',badgeColor:'#10b981'},
  {id:614,cat:'Foreign Movies',type:'movie',name:'John Wick 4',nameAr:'جون ويك 4',desc:'معركة البقاء الأخيرة لجون ويك.',image:'https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_FMjpg_UX1000_.jpg',colors:['#0d0d0d','#d4af37'],streamUrl:'',quality:'4K',lang:'en',year:2023,duration:169,rating:7.7,genre:{ar:'أكشن',en:'Action'}},
  {id:615,cat:'Foreign Movies',type:'movie',name:'The Batman',nameAr:'الباتمان',desc:'باتمان الشاب يكشف فساداً عميقاً في غوثام.',image:'https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTI5NjM@._V1_FMjpg_UX1000_.jpg',colors:['#0d0d0d','#c8a84b'],streamUrl:'',quality:'4K',lang:'en',year:2022,duration:176,rating:7.8,genre:{ar:'أكشن',en:'Action'},badge:'4K',badgeColor:'#7c3aed'},
];